on:
  repository_dispatch:
    types: [opened, deleted]


jobs:
  prod:
    name: Manual trigger event
    runs-on: ubuntu-latest
    steps:
      - run: echo "manual event > workflow_dispatch"

      