name: Manual trigger - workflow_dispatch from Github API

on:
  push:
    
    
jobs:
  prod:
    name: Manual trigger event
    if: ${{ github.ref }} == 'refs/heads/wassim'
    runs-on: ubuntu-latest
    steps:
      - run: echo "run Id > ${{ github.run_id }}"


      
      
      
      
