name: A workflow for my Hello World file
on: 
  push:
    branches:
      - dev
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "this is limited to dev branch only!"
