name: Manual trigger - workflow_dispatch from Github API

on:
  workflow_dispatch:
    inputs: 
      MY_NAME:
        description: hello word
        required: true
        default: wassim kaouia
    
    
jobs:
  prod:
    name: Manual trigger event
    runs-on: ubuntu-latest
    steps:
      - run: echo "manual event > hello ${{ github.event.inputs.MY_NAME }}"
      - run: echo "run Id > ${{ github.run_id }}"


      
      
      
      
